export interface FooterLink {
  description: string;
  icon: string;
  url: string;
}
export interface SEOProps {
  /**
   * Used for Discord, PWA…
   *
   * **Default**: `undefined`
   * */
  siteName?: string;

  /**
   * Used for window / tab title, search engines results, social networks…
   *
   * **Default**: `undefined`
   * */
  title?: string;

  /**
   * Used for search engines results, social networks…
   *
   * **Default**: `undefined`
   * */
  description?: string;

  /**
   * Image URL, preferably absolute and 1200x630px  \
   * Used for social networks…
   *
   * **Default**: `assets/social.png`
   * */
  image?: string;

  /**
   * Favicon SVG
   *
   * **Default**: `true`
   * */
  favicon?: boolean;

  /**
   * Apple touch icon
   *
   * **Default**:`undefined`
   * */
  appleTouchIcon?: string;

  /**
   * Favicon SVG
   *
   * **Default**: `undefined`
   * */
  faviconSvg?: string;
  /**
   * **Default**: `undefined`
   * */
  author?: string;

  /**
   * **Default**: `undefined`
   * */
  copyright?: string;

  /**
   * Reference the `sitemap-index.xml`
   * which is generated by `@astrojs/sitemap`
   *
   * Otherwise crawlers likely prefer `sitemap.xml`
   *
   * **Default**: `true`
   * */
  astroSitemap?: boolean;

  /**
   * **Default**: `Astro.url`
   *
   * (with base from `site` in Astro root config.)
   * */
  canonicalUrl?: string;

  /**
   * **Default**: `'website'`
   * */
  type?: string;

  /**
   * Adds
   * `<meta name="generator" content={Astro.generator} />`
   *
   * **Default**: `true`
   * */
  astroGenerator?: boolean;

  /**
   * Adds
   * `<meta name="viewport" content={viewport} />`
   * if `viewport` is defined
   * **Default**: `width=device-width`
   */
  viewport?: string;
}
